# Configuration for robot odometry EKF

frequency: 100

two_d_mode: true

publish_tf: false

odom_frame: /odom
base_link_frame: base_link
world_frame: /odom

odom0: /robot/odom
odom0_config: [false, false, false,
              false, false, true,
              true, true, false,
              false, false, true,
              false, false, false]
odom0_differential: false

imu0: /imu
imu0_config: [false, false, false,
              false, false, true,
              true, true, false,
              false, false, true,
              false, false, false]
imu0_differential: false